language: node_js
node_js:
- '5.1'
notifications:
  hipchat:
    rooms:
      secure: RQMnJbydp1+rVZtOmc8TaDmGI+yKZtgTFofuqveqxlLJktNhnyZ+eXkfmqTfb+0l/IbpB+ivnk2wbxMRsYSd10AE40fv9QwoAtufsNrqTvRl2jf90qLEnHvqPvehWylz60QZ/5WSKFqYLECb2TowiumcUtQDe7ykPuI2p92R0P8=
